-- Query 2: Which employees are the top 5 sales representatives?
-- This query calculates the total sales amount generated by each employee.

SELECT
    e.FirstName || ' ' || e.LastName AS EmployeeName,
    ROUND(SUM(od.UnitPrice * od.Quantity)::numeric, 2) AS TotalSales
FROM
    Employees e
JOIN
    Orders o ON e.EmployeeID = o.EmployeeID
JOIN
    "Order Details" od ON o.OrderID = od.OrderID
GROUP BY
    EmployeeName
ORDER BY
    TotalSales DESC
LIMIT 5;